apiVersion: v1
kind: Pod
metadata: 
  name: busybox-configmap-pod
spec:
  containers:
  - name: busybox-container
    image: busybox:1.30.1
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
    env:
    - name: pod-app-settings
      valueFrom:
        configMapKeyRef:
          name: app-settings
          key: apply_user_rbac