apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  initContainers:
  - name: init-create-dir
    image: alpine
    command: ['sh', '-c', 'sleep 5 && echo "creating a log directory" && mkdir -p /opt/log']
    volumeMounts:
    - name: data
      mountPath: /opt

  containers:
  - name: app1
    image: alpine
    command: ['sh', '-c', 'echo "app1 is now running" && sleep infinity']
    volumeMounts:
    - name: data
      mountPath: /opt

  volumes:
  - name: data
    emptyDir: {}