apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: container1
    volumentMounts:
    - mountPath: /demovol
    name: demo-volument

  volumes:
  - name: demo-volume
    emptyDir: {}