apiVersion: v1
kind: Pod

metadata:
  name: pod-with-pvc

spec:
  containers:
  - name: container1
    image: nginx
    volumeMounts:
    - name: volume1
      mountPath: /data

  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: pvc1