apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
    volumeMounts:
    - mountPath: /projects # here it can be anything
      name: projects-vol

  volumes:
  - name: projects-vol
    nfs:
      server: 10.224.0.223 # IP of NFS server
      path: /projects # folder using for remote storage on NFS server