apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: pvc1

  containers:
  - image: busybox:latest
    name: busybox-container
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
    volumeMounts:
    - mountPath: "/dynamic-vol"
      name: vol1