apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: admin
  password: 123Passw0rd

---

apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-from-manifest
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-from-manifest
          key: password