apiVersion: v1
kind: Pod
metadata: 
  name: busybox-configmap-pod
  namespace: team2
spec:
  containers:
  - name: busybox-container
    image: busybox:1.30.1
    command: ['sh', '-c', 'while true; do date; sleep 3; done']