apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-limits
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-pods
spec:
  hard:
    pods: "2"

--- 
apiVersion: v1
kind: Pod
metadata:
  name: quota-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu:"400m"