apiVersion: v1
kind: Service

metadata:
  name: hello-world

spec:
  type: NodePort
  selector:
    app: hello-world # pod labels
  ports:
  - protocol: TCP
    port: 8080 # port exposes within the cluster
    targetPort: 80
    nodePort: 30036 # assigned by k8s if not precised