apiVersion: v1
kind: Service

metadata:
  name: Backend

spec:
  type: ClusterIp # can be NodePort or NodePort
  ports:
  - targetPort: 80
    port: 80

  selector:
   name: pod1
   type: front-end-app