apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
  - name: redispod
    image: redis

  volumeMounts:
  - name: configmap1
    mountPath: "/etc/configmap1"
    readONly: true

  volumes:
  - name: configmap1
    configMap:
      name: myconfigmap